name: Build and Deploy Angular Project

on:
  push:
    branches:
      - 'main'

jobs:
  publish:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' 

      - name: Install dependencies
        run: |
          npm install

      - name: Build the Angular project
        run: |
          npm run build --prod 

      - name: Deploy to GitHub Pages
        uses: rayluo/github-pages-overwriter@v1.3
        with:
          source-directory: dist/profile-page 
          target-branch: gh-pages